'use strict';

module.exports = {
  TrackerCapabilities: {
    WIFI_ZONE: ['in_power_saving_zone', 'power_saving_zone'],
    LT: ['live_tracking'],
    BUZZER: ['buzzer_control'],
    LED: ['led_control'],
  },
  TrackerNames: {
    TG4410: 'Tractive LTE',
    'TG4XL_GREEN-TEXTURE': 'Tractive GPS DOG XL',
    'TG5_DARKBLUE-TEXTURE-NORTHAMERICA': 'Tractive GPS CAT Mini',
    'TG5_DARKBLUE-TEXTURE-WORLDWIDE': 'Tractive GPS CAT Mini',
    TRATR1: 'Tractive GPS Classic',
    TRATR1_HUNTER: 'Tractive GPS Classic Hunters',
    TRATR1_PINK: 'Tractive GPS Pink Edition',
    TRATR3G: 'Tractive GPS 3G',
    TRAXL1: 'Tractive GPS Classic XL',
    TRCAT1: 'Tractive GPS CAT',
    TRDOG1: 'Tractive GPS DOG',
    TRDOG1_IKATI: 'Tractive IKATI',
    TRGPS2: 'Tractive GPS2',
    TRNJA4: 'Tractive LTE',
    'TRNJA4_BLUE-LIGHTBLUE': 'Tractive LTE',
    'TRNJA4_BLUE-WHITE': 'Tractive LTE',
    TRNJA4_DARKBLUE: 'Tractive LTE',
    'TRNJA4_DARKBLUE-TEXTURE': 'Tractive CAT LTE',
    'TRNJA4_PINK-ROSE': 'Tractive LTE',
    TRNJA4_YELLOW: 'Tractive LTE',
  },
  TrackerNamesBySku: {
    TRAHU1: 'Tractive GPS Classic Hunters',
    TRAJPWH: 'Tractive LTE',
    TRAMINDB: 'Tractive CAT LTE',
    TRAPI1: 'Tractive GPS Pink Edition',
    TRATR1: 'Tractive GPS Classic',
    TRATR3G: 'Tractive GPS 3G',
    TRAXL1: 'Tractive GPS Classic XL',
    TRCAT1: 'Tractive GPS CAT',
    TRCAT5DB: 'Tractive GPS CAT Mini',
    TRCAT5DBNA: 'Tractive GPS CAT Mini',
    TRDOG1: 'Tractive GPS DOG',
    TRDOG4XLGR: 'Tractive GPS DOG XL',
    TRGPS2: 'Tractive GPS2',
    TRKAT1: 'Tractie IKATI',
    TRNJA4: 'Tractive LTE',
    TRNJABL: 'Tractive LTE',
    TRNJADB: 'Tractive LTE',
    TRNJAPI: 'Tractive LTE',
    TRNJAWH: 'Tractive LTE',
    TRNJAYE: 'Tractive LTE',
  },
};
